# Generated by Django 2.0.5 on 2018-06-05 15:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این دسته بندی', max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شما')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('text', models.TextField(verbose_name='متن دیدگاه')),
                ('date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='زمان انتشار')),
                ('accepted', models.BooleanField(default=False, verbose_name='تایید شده؟')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=150, verbose_name='عنوان سایت')),
                ('Description', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='توضیحات سایت')),
                ('Footer', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='متن فوتر')),
                ('PostNumber', models.PositiveSmallIntegerField(default=10, verbose_name='تعداد مطالب قابل نمایش در صفحه اصلی')),
                ('CommentsDisable', models.BooleanField(default=False, verbose_name='غیرفعالسازی ارسال دیدگاه')),
                ('SiteClose', models.BooleanField(default=False, verbose_name='سایت در دست تعمیر؟')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی',
                'verbose_name_plural': 'تنظیمات عمومی',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='چیدمان')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'فهرست',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این برگه', max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('published_date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'برگه',
                'verbose_name_plural': 'برگه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این نوشته', max_length=100, unique=True)),
                ('published_date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='زمان انتشار')),
                ('modified_date', django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='زمان ویرایش')),
                ('description', models.TextField(help_text='توضیحات مختصری درباره\u200cی این نوشته', verbose_name='متن معرفی')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='این متن در صفحه اصلی نوشته نمایش داده می\u200cشود', verbose_name='متن اصلی')),
                ('tags', tagging.fields.TagField(blank=True, help_text='با استفاده از کاما (,) آنها را از یکدیگر جدا نمایید', max_length=255, verbose_name='برچسب\u200cها')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته ها',
                'ordering': ['published_date'],
            },
        ),
        migrations.AddField(
            model_name='navbar',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Page', verbose_name='برگه'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='نوشته'),
        ),
    ]
