# Generated by Django 5.2 on 2026-04-18 20:31

import django.db.models.deletion
import django_ckeditor_5.fields
import django_jalali.db.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این دسته بندی', max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_index=True, max_length=150, verbose_name='عنوان سایت')),
                ('Description', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='توضیحات سایت')),
                ('Footer', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='متن فوتر')),
                ('PostNumber', models.PositiveSmallIntegerField(default=10, verbose_name='تعداد مطالب قابل نمایش در صفحه اصلی')),
                ('CommentsDisable', models.BooleanField(default=False, verbose_name='غیرفعالسازی ارسال دیدگاه')),
                ('SiteClose', models.BooleanField(default=False, verbose_name='سایت در دست تعمیر؟')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی',
                'verbose_name_plural': 'تنظیمات عمومی',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این برگه', max_length=100, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا')),
                ('published_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'برگه',
                'verbose_name_plural': 'برگه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='چیدمان')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.page', verbose_name='برگه')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'فهرست',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='نام انگلیسی برای استفاده در لینک این نوشته', max_length=100, unique=True)),
                ('published_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('modified_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('description', models.TextField(help_text='توضیحات مختصری درباره\u200cی این نوشته', verbose_name='متن معرفی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='این متن در صفحه اصلی نوشته نمایش داده می\u200cشود', verbose_name='متن اصلی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته بندی')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته ها',
                'ordering': ['published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شما')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('text', models.TextField(verbose_name='متن دیدگاه')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('accepted', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='نوشته')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ['-date'],
            },
        ),
    ]
