# Generated by Django 2.0.5 on 2018-06-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
    ]
