# Generated by Django 2.0.5 on 2018-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180524_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
    ]
