# Generated by Django 2.0.5 on 2018-05-18 10:30

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
